package gov.wsclient.orderservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-10-05T19:18:46.208+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://rol.rw/firstWebServiceTesting", name = "CustomerOrdersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerOrdersPortType {

    @WebMethod
    @WebResult(name = "createOrderResponse", targetNamespace = "http://rol.rw/firstWebServiceTesting", partName = "createOrderResponse")
    public CreateOrderResponse createOrders(
        @WebParam(partName = "createOrderRequest", name = "createOrderRequest", targetNamespace = "http://rol.rw/firstWebServiceTesting")
        CreateOrderRequest createOrderRequest
    );

    @WebMethod
    @WebResult(name = "getOrderResponse", targetNamespace = "http://rol.rw/firstWebServiceTesting", partName = "getOrderResponse")
    public GetOrderResponse getOrders(
        @WebParam(partName = "getOrderRequest", name = "getOrderRequest", targetNamespace = "http://rol.rw/firstWebServiceTesting")
        GetOrderRequest getOrderRequest
    );
}
